fix: tf-plan id in terraform plan

diff --git a/.github/workflows/tf-plan-apply.yml b/.github/workflows/tf-plan-apply.yml
--- a/.github/workflows/tf-plan-apply.yml
+++ b/.github/workflows/tf-plan-apply.yml
@@ -52,26 +52,26 @@ jobs:
       id: fmt
       run: terraform fmt -check
 
-    # Generates an execution plan for Terraform
-    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    # # Generates an execution plan for Terraform
+    # # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    # - name: Terraform Plan
+    #   id: tf-plan
+    #   run: |
+    #     export exitcode=0
+    #     terraform plan -detailed-exitcode -no-color -out=tfplan || export exitcode=$?
+
+    #     echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+    #     if [ $exitcode -eq 1 ]; then
+    #       echo Terraform Plan Failed!
+    #       exit 1
+    #     else
+    #       exit 0
+    #     fi
+
     - name: Terraform Plan
       id: tf-plan
-      run: |
-        export exitcode=0
-        terraform plan -detailed-exitcode -no-color -out=tfplan || export exitcode=$?
-
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else
-          exit 0
-        fi
-
-    # - name: Terraform Plan
-    #   id: plan
-    #   run: terraform plan -input=false -no-color -out=tfplan -detailed-exitcode
+      run: terraform plan -input=false -no-color -out=tfplan -detailed-exitcode
 
     # Save plan to artifacts
     - name: Publish Terraform Plan
