test

diff --git a/.github/workflows/tf-plan-apply.yml b/.github/workflows/tf-plan-apply.yml
--- a/.github/workflows/tf-plan-apply.yml
+++ b/.github/workflows/tf-plan-apply.yml
@@ -53,20 +53,24 @@ jobs:
 
     # Generates an execution plan for Terraform
     # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    # - name: Terraform Plan
+    #   id: tf-plan
+    #   run: |
+    #     export exitcode=0
+    #     terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+
+    #     echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+    #     if [ $exitcode -eq 1 ]; then
+    #       echo Terraform Plan Failed!
+    #       exit 1
+    #     else
+    #       exit 0
+    #     fi
+
     - name: Terraform Plan
-      id: tf-plan
-      run: |
-        export exitcode=0
-        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
-
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else
-          exit 0
-        fi
+      id: plan
+      run: terraform plan -input=false -no-color -out=tfplan -detailed-exitcode
 
     # Save plan to artifacts
     - name: Publish Terraform Plan
@@ -75,22 +79,22 @@ jobs:
         name: tfplan
         path: tfplan
 
-    # Create string output of Terraform Plan
-    - name: Create String Output
-      id: tf-plan-string
-      run: |
-        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+    # # Create string output of Terraform Plan
+    # - name: Create String Output
+    #   id: tf-plan-string
+    #   run: |
+    #     TERRAFORM_PLAN=$(terraform show -no-color tfplan)
 
-        delimiter="$(openssl rand -hex 8)"
-        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
-        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
-        echo "" >> $GITHUB_OUTPUT
-        echo '```terraform' >> $GITHUB_OUTPUT
-        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
-        echo '```' >> $GITHUB_OUTPUT
-        echo "</details>" >> $GITHUB_OUTPUT
-        echo "${delimiter}" >> $GITHUB_OUTPUT
+    #     delimiter="$(openssl rand -hex 8)"
+    #     echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+    #     echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+    #     echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+    #     echo "" >> $GITHUB_OUTPUT
+    #     echo '```terraform' >> $GITHUB_OUTPUT
+    #     echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+    #     echo '```' >> $GITHUB_OUTPUT
+    #     echo "</details>" >> $GITHUB_OUTPUT
+    #     echo "${delimiter}" >> $GITHUB_OUTPUT
 
     # Publish Terraform Plan as task summary
     # - name: Publish Terraform Plan to Task Summary
